version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: demok_db
    restart: always
    environment:
      POSTGRES_USER: demok_user
      POSTGRES_PASSWORD: demok_password
      POSTGRES_DB: demok_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
