// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC0qnVseVVN6oVGH3-rKXiOgurM35UrPo',
    appId: '1:1087284539439:web:c17a0fa44044152258d6da',
    messagingSenderId: '1087284539439',
    projectId: 'demok-ba1a1',
    authDomain: 'demok-ba1a1.firebaseapp.com',
    storageBucket: 'demok-ba1a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6x9-HN_l7beII-tB3ndZwik_WPNHmeQ',
    appId: '1:1087284539439:android:0e0683c253245b4258d6da',
    messagingSenderId: '1087284539439',
    projectId: 'demok-ba1a1',
    storageBucket: 'demok-ba1a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvL8UBvxEWi0sj00Ii_-8eJmBo1M9_ZDI',
    appId: '1:1087284539439:ios:07749c0ecb9ed84b58d6da',
    messagingSenderId: '1087284539439',
    projectId: 'demok-ba1a1',
    storageBucket: 'demok-ba1a1.firebasestorage.app',
    iosBundleId: 'com.example.demokMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvL8UBvxEWi0sj00Ii_-8eJmBo1M9_ZDI',
    appId: '1:1087284539439:ios:07749c0ecb9ed84b58d6da',
    messagingSenderId: '1087284539439',
    projectId: 'demok-ba1a1',
    storageBucket: 'demok-ba1a1.firebasestorage.app',
    iosBundleId: 'com.example.demokMobile',
  );
}
